spring.application.name=airbnb-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/airbnb_db
spring.datasource.username=airbnb_user
spring.datasource.password=airbnb_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

server.servlet.context-path=/api/v1